add RTC
luojia65/w806-pac pull request #3
Opened 2021-11-16 06:41 UTC by apeng2012

2021-11-16 06:46 UTC, luojia65 commented
你好，我在文件里提供了一些格式上的修改意见。另外，你会完成整个PMU模块吗？还是只是PMU模块的rtc部分

2021-11-16 07:57 UTC, apeng2012 commented
会继续完成PMU，最近摸鱼的时间比较多。

2021-11-17 01:32 UTC, apeng2012 commented
"我在文件里提供了一些格式上的修改意见。"   啥文件？

为什么没有merge? 我这次提交的哪里需要修改？还是等PMU弄完一起合并

2021-11-17 02:58 UTC, luojia65 commented
@apeng2012 github pull request里有start a review，上面有较多的留言。我希望在整个pmu完成之后再一起合并（并非不肯定你的工作，而是它如果更完整，更适合rust嵌入式开发，会更好）

2021-11-17 05:32 UTC, apeng2012 commented
ok PMU 一起合并

没找到 **start a review** ，baidu也没搜到操作方法。再麻烦你说详细点，或者给个链接我去学一下。

2021-11-17 05:36 UTC, luojia65 commented
@apeng2012 你那里没有显示吗？或者直接点击Files菜单栏看看：https://github.com/luojia65/w806-pac/pull/3/files

2021-11-17 05:48 UTC, apeng2012 commented
你给的链接内容如下。  只显示我提交的。
```
@@ -37,17 +37,124 @@
        </register>
      </registers>
    </peripheral>

    <!-- PMU RTC -->
    <peripheral>
      <name>PMU</name>
      <baseAddress>0x40000D00</baseAddress>
      <description>Power management unit</description>
      <registers>
        <!-- RTC R1: RTC Register 1 -->
        <register>
          <name>todo</name>
          <description>??</description>
          <addressOffset>0</addressOffset>
          <name>RTC_R1</name>
          <description>RTC Register 1</description>
          <addressOffset>0x0C</addressOffset>
          <size>32</size>
          <access>read-write</access>
          <resetValue>0x00000000</resetValue>
          <resetMask>0x9F1F3F3F</resetMask>

          <fields>
            <!-- todo: fields -->
            <!-- ALRIE: Alarm Interrupt Enable -->
            <field>
              <name>ALRIE</name>
              <description>Alarm Interrupt Enable</description>
              <bitRange>[31:31]</bitRange>
              <access>read-write</access>
              <enumeratedValues>
                <enumeratedValue>
                  <name>Disabled</name>
                  <description>RTC does not generate Alarm Interrupts</description>
                  <value>0</value>
                </enumeratedValue>
                <enumeratedValue>
                  <name>Enable</name>
                  <description>RTC triggers the Alarm Interrupt</description>
                  <value>1</value>
                </enumeratedValue>
              </enumeratedValues>
            </field>

            <!-- DAY -->
            <field>
              <name>DAY</name>
              <description>day</description>
              <bitRange>[28:24]</bitRange>
              <access>read-write</access>
            </field>

            <!-- HOUR -->
            <field>
              <name>HOUR</name>
              <description>hour</description>
              <bitRange>[20:16]</bitRange>
              <access>read-write</access>
            </field>

            <!-- MINUTE -->
            <field>
              <name>MINUTE</name>
              <description>minute</description>
              <bitRange>[13:8]</bitRange>
              <access>read-write</access>
            </field>

            <!-- SECOND -->
            <field>
              <name>SECOND</name>
              <description>second</description>
              <bitRange>[5:0]</bitRange>
              <access>read-write</access>
            </field>
          </fields>
        </register>

        <!-- RTC R2: RTC Register 2 -->
        <register>
          <name>RTC_R2</name>
          <description>RTC Register 2</description>
          <addressOffset>0x10</addressOffset>
          <size>32</size>
          <access>read-write</access>
          <resetValue>0x00000000</resetValue>
          <resetMask>0x00017F0F</resetMask>

          <fields>
            <!-- EN: RTC Enable -->
            <field>
            <name>EN</name>
              <description>RTC Enable</description>
              <bitRange>[16:16]</bitRange>
              <access>read-write</access>
              <enumeratedValues>
                <enumeratedValue>
                  <name>Disabled</name>
                  <description>RTC disable</description>
                  <value>0</value>
                </enumeratedValue>
                <enumeratedValue>
                  <name>Enable</name>
                  <description>RTC enable</description>
                  <value>1</value>
                </enumeratedValue>
              </enumeratedValues>
            </field>

            <!-- YEAR -->
            <field>
              <name>YEAR</name>
              <description>year</description>
              <bitRange>[14:8]</bitRange>
              <access>read-write</access>
            </field>

            <!-- MONTH -->
            <field>
              <name>MONTH</name>
              <description>month</description>
              <bitRange>[3:0]</bitRange>
              <access>read-write</access>
            </field>
          </fields>
        </register>
      </registers>
```

2021-11-17 05:54 UTC, luojia65 requested changes
提交评价

2021-11-17 05:54 UTC, luojia65 commented on w806.svd
> +    <!-- PMU RTC -->
我们在阅读svd文件的时候，name和description字段已经足够解释这个寄存器了，或许可以考虑不添加额外的重复注释和空行。下面register、field上也是相同的。

2021-11-17 05:54 UTC, luojia65 commented on w806.svd
> +            <!-- DAY -->
同上

2021-11-17 05:54 UTC, luojia65 commented on w806.svd
> +                  <name>Disabled</name>
如果这里是“disable”，或许会和下面的“enable”对应地更好

2021-11-17 05:54 UTC, luojia65 commented on w806.svd
> +              <access>read-write</access>
如果整个寄存器权限都是read-write（不包括保留的位，这部分在“resetMask”里已经给定了），尽量在`<register>`级别定义“access”项目，此时每个field中就不需要再次定义了。

2021-11-17 05:54 UTC, luojia65 commented on w806.svd
> +          <name>RTC_R1</name>
我们可以考虑更适合人类阅读的寄存器名字，这样svd2rust在生成支持库之后，rust开发者能够更好地阅读支持库的代码。
比如说在PMU中有以下的寄存器，可以这样在svd文件中体现：
```
PMU 控制寄存器 => control
PMU 定时器 0 => timer_0
保留 => 保留寄存器不需要编写<register>，写一个注释说明即可
RTC 配置寄存器 1 => rtc_register_1
RTC 配置寄存器 2 => rtc_register_2
PMU 中断源寄存器（提供 PMU 中断标志） => interrupt_flag
```
对寄存器的位，可以选择完整的名字，让语义更通顺。比如：
```
RTC 计时功能使能位 => alarm_interrupt
年初值/年定时值  => year （这里你已经做得很好了！）
月初值/月定时值  => month （同上）
```
可以考虑在rust代码的实际使用中，更通顺地编写控制寄存器位的代码。比如：`pmu.rtc_register_1().modify(|_, w| w.alarm_interrupt().enable())`

2021-11-17 05:55 UTC, luojia65 commented
@apeng2012 😂抱歉我之前review changes之后没有点击提交按钮，可能只有我本地可见，现在看看出来了吗

2021-11-17 06:14 UTC, apeng2012 commented on w806.svd
> +    <!-- PMU RTC -->
这个注释还是很有用的。

1. 一般编辑器都能 一段一段的折叠，如果没有注释就会看到
```
<peripheral>
</peripheral>
<peripheral>
</peripheral>
```
加上注释会好很多
```
<!-- PMU RTC -->
<peripheral>
</peripheral>

<!-- RCC -->
<peripheral>
</peripheral>
```
通过折叠，你能很方便了解有哪些外设。

2. 注释的配色与内容不同更醒目。
3. 我参考官方例子 [https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_Example_pg.html](https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_Example_pg.html)

2021-11-17 06:14 UTC, apeng2012 commented on w806.svd
> +            <!-- DAY -->
同上

2021-11-17 06:15 UTC, apeng2012 commented on w806.svd
> +                  <name>Disabled</name>
好的，我仔细检查一下

2021-11-17 06:15 UTC, apeng2012 commented on w806.svd
> +              <access>read-write</access>
学习了

2021-11-17 06:31 UTC, apeng2012 commented on w806.svd
> +          <name>RTC_R1</name>
嗯。事关以后程序的调用，应该好好审查一下。

2021-11-18 02:05 UTC, luojia65 approved these changes

2021-11-18 02:12 UTC, luojia65 commented on w806.svd
> +              <bitRange>[4:4]</bitRange>
w800文档显示的是[5:5]（2.1版）

2021-11-18 03:11 UTC, apeng2012 commented on w806.svd
> +              <bitRange>[4:4]</bitRange>
#define PMU_IF_RTC_Pos						(4)

[https://github.com/luojia65/w806-pac/issues/5](https://github.com/luojia65/w806-pac/issues/5)

2021-11-18 03:56 UTC, luojia65 commented
如果没有补充的内容，我觉得可以合并了，还有要补充的内容吗？
稍后项目会添加一个贡献者名单，感谢你对项目的贡献。

2021-11-18 04:56 UTC, apeng2012 commented
没有要补充的了。
不客气。开发板已经买了，希望能尽快用rust开发。
有HAL库开发的话，希望能够参与。

2021-11-18 05:34 UTC, merged

2021-11-18 05:47 UTC, luojia65 commented on w806.svd
> +                  <name>on</name>
这里做得很好！on和off很符合语义。